name: App release Android

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    name: Build apk release arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Storing key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/app/key.properties

      - name: Storing keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/siarAppRelease.keystore

      - name: Build application
        run: yarn install && cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release v0.1.18
            - Bump dependencies RN 0.74.5
          draft: false
          prerelease: false

      - name: Upload .apks to artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          asset_name: "app bundle"
          overwrite: true
          file_glob: true
          file: android/app/build/outputs/apk/release/app-*

